# Generated by Django 4.2.1 on 2023-05-31 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_crypto', models.IntegerField(verbose_name='Id cryptomoney')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Цена закупки')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Количество')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолии',
            },
        ),
    ]
