# Generated by Django 4.2.1 on 2023-06-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id_crypto',
            field=models.CharField(max_length=20, verbose_name='Id crypto coin'),
        ),
    ]
